export { default as BackgroundMobile } from "./background-mobile.png";
export { default as Background } from "./background.png";
export { default as CategoryCard1 } from "./card-category01.png";
export { default as CategoryCard2 } from "./card-category02.png";
export { default as CategoryCard3 } from "./card-category03.png";
export { default as CategoryCard4 } from "./card-category04.png";
export { default as CategoryCard5 } from "./card-category05.png";
export { default as NoneImageBgMobile } from "./none-image-bg-mobile.png";
export { default as NoneImageBg } from "./none-image-bg.png";
